:page-layout: default
:page-title: Options
:page-nav_order: 3
:page-show-toc: true

= Options
:toc: preamble

[.fs-6.fw-300]
Konvert provides a few options, which you can define either globally for the complete run, or per mapping.

== How to set options

=== Globally with Gradle

If you use gradle, you can define options using the `ksp` block:

[source,kotlin]
----
ksp {
    arg("konvert.konverter.generate-class", "true")
}
----

=== Globally with Maven

If you use maven together with the `com.dyescape:kotlin-maven-symbol-processing` dependency (as shown here TODO), you can add options to your `pom.xml` in the `<configuration>` block of `kotlin-maven-plugin`:

[source,xml]
----
<pluginOptions>
    <option>ksp:apoption=konvert.konverter.generate-class=true</option>
</pluginOptions>
----

=== Local for one annotation

The annotations `@Konverter`, `@Konvert`, `@KonvertTo` and `@KonvertFrom` all offer the possibility to set options.
The processing of these annotations will run with a copy of the inherited options (e.g. globally set ones) combined with their defined options.
In case you have options in `@Konverter` and `@Konvert`, then the later one will inherit the other options and override/complement with its own.

[source,kotlin]
----
@Konverter(options=[
    Konfig(key="konvert.enforce-not-null", value="true")
])
----

== Available Options

=== General Options

[cols="4,1,1,7"]
|===
|Option |Possible values |Default |Description

a|`*konvert.enforce-not-null*`
a|`true`/`false`
a|`false`
a|When set to `true`, all `TypeConverter` which respect this setting:

* will match, when the source type is nullable but the target type is not
* will add `!!` to the generated code, to enforce the result to be not null

4+a|
[.pl-6]
.Example
[%collapsible]
====
[source,kotlin]
----
@KonvertTo(Person::class, options=[
    Konfig(key="konvert.enforce-not-null", value="true")
])
class PersonDto(val name: String?)
class Person(val name: String)
----
Will generate:
[source,kotlin]
----
fun PersonDto.toPerson() = Person(name = name!!)
----
====

a|`*konvert.generated-filename-suffix*`
a|any string
a|`Konverter`
a|This setting will change the suffix/trailing part of the generated filenames.

4+a|
[.pl-6]
.Example
[%collapsible]
====
[source,kotlin]
----
@KonvertTo(PersonDto::class, options=[
    Konfig(key="konvert.generated-filename-suffix", value="_XX")
])
class Person(val name: String)
class PersonDto(val name: String)
----
Will generate a file `Person_XX.kt` instead of `PersonKonverter.kt`
====

a|`*konvert.add-generated-konverter-annotation*`
a|`true`/`false`
a|`true`
a|This setting will add the `@GeneratedKonverter` annotation on the generated functions. Together with a file being written to META-INF containing all generated functions FQN, this annotation is used to reuse previously generated konverter functions from other modules or libraries.
If you do not want your generated konverter functions to be reused in other modules, you can turn this setting globally or per annotation.

4+a|
[.pl-6]
.Example
[%collapsible]
====
[source,kotlin]
----
@KonvertTo(PersonDto::class, priority = 123)
class Person(val name: String)
@KonvertTo(Person::class, options=[
    Konfig(key="konvert.add-generated-konverter-annotation", value="false")
])
class PersonDto(val name: String)
----
Will generate:
[source,kotlin]
----
@GeneratedKonverter(priority = 123)
fun Person.toPersonDto() = PersonDto(name = name)
fun PersonDto.toPerson() = Person(name = name)
----
====

a|`*konvert.enable-converters*`
a|list of `TypeConverter` names divided by comma or semicolon
a|empty list
a|All listed `TypeConverter` names are registered to be enabled in the current context.
This can be useful if you need a certain `TypeConverter`, e.g. `StringToIntConverter`, a lot of times
and do not want to enable it on each field mapping via `@Mapping`.

4+a|
[.pl-6]
.Example
[%collapsible]
====
[source,kotlin]
----
@KonvertTo(PersonDto::class, options=[
    Konfig(key="konvert.enable-converters", value="StringToIntConverter, StringToLocalDateConverter")
])
class Person(val age: String, val birthday: String)
class PersonDto(val age: Int, val birthday: LocalDate)
----
====

|===

=== `@Konverter` Options

[cols="4,1,1,7"]
|===
|Option |Possible values |Default |Description

a|`*konvert.konverter.generate-class*`
a|`true`/`false`
a|`false`
a|When set to `true`, Konvert will generate a `class` instead of an `object`.


4+a|
[.pl-6]
.Example
[%collapsible]
====
[source,kotlin]
----
@Konverter(options=[
    Konfig(key="konvert.konverter.generate-class", value="true")
])
interface PersonMapper {
    fun toDto(person: Person): PersonDto
}

class PersonDto(val name: String)
class Person(val name: String)
----
Will generate:
[source,kotlin]
----
class PersonMapperImpl: PersonMapper {
    override fun toDto(person: Person): PersonDto = PersonDto(name = person.name)
}
----
====

|===

=== Injector Options

==== Anvil

[cols="4,1,1,7"]
|===
|Option |Possible values |Default |Description

a|`*konvert.anvil.default-injection-method*`
a|`DISABLED`, `FACTORY`, `SINGLETON`
a|`DISABLED`
a|Append some injection method by default to all generated mapper classes. Requires `konvert.anvil.default-scope` to be set as well!

a|`*konvert.anvil.default-scope*`
a|fully qualified class name
a|`-`
a|Has to be set to qualified name of anvil scope class, like AppScope. Only used when `konvert.anvil.default-injection-method` not disabled.

4+a|
[.pl-6]
.Example
[%collapsible]
====
Global settings (e.g. in `build.gradle.kts` or `pom.xml`):

* `konvert.anvil.default-injection-method` = `SINGLETON`
* `konvert.anvil.default-scope` = `AppScope`

[source,kotlin]
----
abstract class AppScope private constructor()

@Konverter
interface PersonMapper {
    fun toDto(person: Person): PersonDto
}
class Person(val name: String)
class PersonDto(val name: String)
----
Will generate:
[source,kotlin]
----
@ContributesBinding(scope = AppScope::class)
@Singleton
class PersonMapperImpl: PersonMapper {
    @Inject
    public constructor()

    override fun toDto(person: Person): PersonDto = PersonDto(name = person.name)
}
----
====

|===

==== Koin

[cols="4,1,1,7"]
|===
|Option |Possible values |Default |Description

a|`*konvert.koin.default-injection-method*`
a|`DISABLED`, `FACTORY`, `SINGLE`, `SCOPE`
a|`DISABLED`
a|Append some injection method by default to all generated mapper classes. Requires `konvert.koin.default-scope` to be set as well!

a|`*konvert.koin.default-scope*`
a|fully qualified class name or any string
a|`-`
a|Use this scope by default when `konvert.koin.default-injection-method` is set to `scope`.

* If value is fully qualified class identifier it will be used as `@Scope(ProvidedType::class)`.
* If value is string - it will be used as named scope, like `@Scope(name = "ProvidedName")`

4+a|
[.pl-6]
.Example
[%collapsible]
====
Global settings (e.g. in `build.gradle.kts` or `pom.xml`):

* `konvert.koin.default-injection-method` = `SINGLE`

[source,kotlin]
----
@Konverter
interface PersonMapper {
    fun toDto(person: Person): PersonDto
}
class Person(val name: String)
class PersonDto(val name: String)
----
Will generate:
[source,kotlin]
----
@Single
class PersonMapperImpl: PersonMapper {
    override fun toDto(person: Person): PersonDto = PersonDto(name = person.name)
}
----
====

|===
