# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Update dependencies weekly
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update dependencies in /injectors weekly, but ignore minor and patch updates
  - package-ecosystem: "gradle"
    directories: ["/injectors/**"]
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]

  # Update dependencies in /example weekly, but ignore io.mcarle:konvert* dependencies
  - package-ecosystem: "maven"
    directory: "/example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.mcarle:konvert*"

  # Update dependencies in /example weekly, but ignore io.mcarle:konvert* dependencies
  - package-ecosystem: "gradle"
    directory: "/example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.mcarle:konvert*"

  # Disable updates for /docs
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
