# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Update konvert dependencies weekly
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "example/**"
      - "injectors/**" # ignore updates in injectors modules

  # Update direct dependencies in /docs weekly
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
