rootProject.name = "konvert"
include("api")
include("processor")
include("plugin-api")
include("converter")
include("converter-api")
include("injectors:spring-injector")
include("injectors:spring-annotations")
include("injectors:cdi-injector")
include("injectors:cdi-annotations")
include("injectors:koin-injector")
include("injectors:koin-annotations")
include("docs")
