package io.mcarle.lib.kmapper.processor

import io.mcarle.lib.kmapper.annotation.DEFAULT_CONVERTER_PRIORITY
import io.mcarle.lib.kmapper.processor.config.ConverterConfig
import io.mcarle.lib.kmapper.processor.converter.*

object TypeConverterRegistry : Iterable<TypeConverter> {

    private val typeConverterList = sortedMapOf<Int, MutableList<TypeConverter>>()

    val defaultConverter = listOf(
        SameTypeConverter(),
        ToAnyConverter(),
        StringToIntConverter(),
        StringToUIntConverter(),
        StringToLongConverter(),
        StringToULongConverter(),
        StringToShortConverter(),
        StringToUShortConverter(),
        StringToNumberConverter(),
        StringToByteConverter(),
        StringToUByteConverter(),
        StringToCharConverter(),
        StringToBooleanConverter(),
        StringToFloatConverter(),
        StringToDoubleConverter(),
        IntToStringConverter(),
        IntToUIntConverter(),
        IntToLongConverter(),
        IntToULongConverter(),
        IntToShortConverter(),
        IntToUShortConverter(),
        IntToNumberConverter(),
        IntToByteConverter(),
        IntToUByteConverter(),
        IntToCharConverter(),
        IntToBooleanConverter(),
        IntToFloatConverter(),
        IntToDoubleConverter(),
        UIntToStringConverter(),
        UIntToIntConverter(),
        UIntToLongConverter(),
        UIntToULongConverter(),
        UIntToShortConverter(),
        UIntToUShortConverter(),
        UIntToNumberConverter(),
        UIntToByteConverter(),
        UIntToUByteConverter(),
        UIntToCharConverter(),
        UIntToBooleanConverter(),
        UIntToFloatConverter(),
        UIntToDoubleConverter(),
        LongToStringConverter(),
        LongToIntConverter(),
        LongToUIntConverter(),
        LongToULongConverter(),
        LongToShortConverter(),
        LongToUShortConverter(),
        LongToNumberConverter(),
        LongToByteConverter(),
        LongToUByteConverter(),
        LongToCharConverter(),
        LongToBooleanConverter(),
        LongToFloatConverter(),
        LongToDoubleConverter(),
        ULongToStringConverter(),
        ULongToIntConverter(),
        ULongToUIntConverter(),
        ULongToLongConverter(),
        ULongToShortConverter(),
        ULongToUShortConverter(),
        ULongToNumberConverter(),
        ULongToByteConverter(),
        ULongToUByteConverter(),
        ULongToCharConverter(),
        ULongToBooleanConverter(),
        ULongToFloatConverter(),
        ULongToDoubleConverter(),
        ShortToStringConverter(),
        ShortToIntConverter(),
        ShortToUIntConverter(),
        ShortToLongConverter(),
        ShortToULongConverter(),
        ShortToUShortConverter(),
        ShortToNumberConverter(),
        ShortToByteConverter(),
        ShortToUByteConverter(),
        ShortToCharConverter(),
        ShortToBooleanConverter(),
        ShortToFloatConverter(),
        ShortToDoubleConverter(),
        UShortToStringConverter(),
        UShortToIntConverter(),
        UShortToUIntConverter(),
        UShortToLongConverter(),
        UShortToULongConverter(),
        UShortToShortConverter(),
        UShortToNumberConverter(),
        UShortToByteConverter(),
        UShortToUByteConverter(),
        UShortToCharConverter(),
        UShortToBooleanConverter(),
        UShortToFloatConverter(),
        UShortToDoubleConverter(),
        FloatToStringConverter(),
        FloatToIntConverter(),
        FloatToUIntConverter(),
        FloatToLongConverter(),
        FloatToULongConverter(),
        FloatToShortConverter(),
        FloatToUShortConverter(),
        FloatToNumberConverter(),
        FloatToByteConverter(),
        FloatToUByteConverter(),
        FloatToCharConverter(),
        FloatToBooleanConverter(),
        FloatToDoubleConverter(),
        DoubleToStringConverter(),
        DoubleToIntConverter(),
        DoubleToUIntConverter(),
        DoubleToLongConverter(),
        DoubleToULongConverter(),
        DoubleToShortConverter(),
        DoubleToUShortConverter(),
        DoubleToNumberConverter(),
        DoubleToByteConverter(),
        DoubleToUByteConverter(),
        DoubleToCharConverter(),
        DoubleToBooleanConverter(),
        DoubleToFloatConverter(),
        ByteToStringConverter(),
        ByteToIntConverter(),
        ByteToUIntConverter(),
        ByteToLongConverter(),
        ByteToULongConverter(),
        ByteToShortConverter(),
        ByteToUShortConverter(),
        ByteToNumberConverter(),
        ByteToUByteConverter(),
        ByteToDoubleConverter(),
        ByteToCharConverter(),
        ByteToBooleanConverter(),
        ByteToFloatConverter(),
        UByteToStringConverter(),
        UByteToIntConverter(),
        UByteToUIntConverter(),
        UByteToLongConverter(),
        UByteToULongConverter(),
        UByteToShortConverter(),
        UByteToUShortConverter(),
        UByteToNumberConverter(),
        UByteToByteConverter(),
        UByteToCharConverter(),
        UByteToBooleanConverter(),
        UByteToFloatConverter(),
        UByteToDoubleConverter(),
        NumberToStringConverter(),
        NumberToIntConverter(),
        NumberToUIntConverter(),
        NumberToLongConverter(),
        NumberToULongConverter(),
        NumberToShortConverter(),
        NumberToUShortConverter(),
        NumberToByteConverter(),
        NumberToUByteConverter(),
        NumberToCharConverter(),
        NumberToBooleanConverter(),
        NumberToFloatConverter(),
        NumberToDoubleConverter(),
        CharToStringConverter(),
        CharToIntConverter(),
        CharToUIntConverter(),
        CharToLongConverter(),
        CharToULongConverter(),
        CharToShortConverter(),
        CharToUShortConverter(),
        CharToNumberConverter(),
        CharToDoubleConverter(),
        CharToByteConverter(),
        CharToUByteConverter(),
        CharToBooleanConverter(),
        CharToFloatConverter(),
        BooleanToStringConverter(),
        BooleanToIntConverter(),
        BooleanToUIntConverter(),
        BooleanToLongConverter(),
        BooleanToULongConverter(),
        BooleanToShortConverter(),
        BooleanToUShortConverter(),
        BooleanToNumberConverter(),
        BooleanToDoubleConverter(),
        BooleanToByteConverter(),
        BooleanToUByteConverter(),
        BooleanToCharConverter(),
        BooleanToFloatConverter(),
        EnumToStringConverter(),
        StringToEnumConverter(),
        EnumToIntConverter(),
        IntToEnumConverter(),
        EnumToUIntConverter(),
        UIntToEnumConverter(),
        EnumToLongConverter(),
        LongToEnumConverter(),
        EnumToULongConverter(),
        ULongToEnumConverter(),
        EnumToShortConverter(),
        ShortToEnumConverter(),
        EnumToUShortConverter(),
        UShortToEnumConverter(),
        EnumToNumberConverter(),
        NumberToEnumConverter(),
        EnumToDoubleConverter(),
        DoubleToEnumConverter(),
        EnumToByteConverter(),
        ByteToEnumConverter(),
        EnumToUByteConverter(),
        UByteToEnumConverter(),
        EnumToCharConverter(),
        EnumToFloatConverter(),
        FloatToEnumConverter(),
        IterableToIterableConverter(),
        MapToMapConverter(),
        EnumToEnumConverter(),
        InstantToStringConverter(),
        ZonedDateTimeToStringConverter(),
        OffsetDateTimeToStringConverter(),
        LocalDateTimeToStringConverter(),
        LocalDateToStringConverter(),
        InstantToLongConverter(),
        ZonedDateTimeToLongConverter(),
        OffsetDateTimeToLongConverter(),
        InstantToDateConverter(),
        ZonedDateTimeToDateConverter(),
        OffsetDateTimeToDateConverter(),
        StringToInstantConverter(),
        StringToZonedDateTimeConverter(),
        StringToOffsetDateTimeConverter(),
        StringToLocalDateTimeConverter(),
        StringToLocalDateConverter(),
        LongToInstantConverter(),
        DateToStringConverter(),
        DateToLongConverter(),
        DateToInstantConverter(),
        StringToDateConverter(),
        LongToDateConverter(),
    )

    init {
        reinitConverterList(*defaultConverter.toTypedArray())
    }

    /**
     * Only for tests!
     */
    internal fun reinitConverterList(vararg typeConverter: TypeConverter) {
        typeConverterList.clear()
        typeConverterList[DEFAULT_CONVERTER_PRIORITY] = typeConverter.toMutableList()
    }

    fun addConverters(order: Int, converterList: List<TypeConverter>) {
        typeConverterList[order] ?: mutableListOf<TypeConverter>().also {
            typeConverterList[order] = it
        } += converterList
    }

    fun initConverters(converterConfig: ConverterConfig) {
        typeConverterList.values.flatten().forEach { it.init(converterConfig) }
    }

    override fun iterator(): Iterator<TypeConverter> {
        return typeConverterList.values.flatten().iterator()
    }
}