package io.mcarle.konvert.converter.api.config

/**
 * Strategy used when `konvert.enforce-not-null = true` and Konvert has to map
 * from a nullable source type to a non-nullable target type.
 *
 * - [ASSERTION_OPERATOR] uses the Kotlin `!!` operator and throws a raw [NullPointerException].
 * - [REQUIRE_NOT_NULL] wraps the access in [requireNotNull] and throws an [IllegalArgumentException]
 *   with a descriptive message generated by the processor.
 */
enum class EnforceNotNullStrategy {

    /**
     * Use the Kotlin not-null assertion operator (`!!`).
     */
    ASSERTION_OPERATOR,

    /**
     * Use [requireNotNull] with a generated error message.
     */
    REQUIRE_NOT_NULL
}

/**
 * Configuration key that controls how Konvert enforces non-nullability when
 * `konvert.enforce-not-null = true`.
 *
 * Possible values:
 *  - "assertion-operator" (default)
 *  - "require-not-null"
 */
const val KONVERT_ENFORCE_NOT_NULL_STRATEGY: String = "konvert.enforce-not-null-strategy"
