package io.mcarle.konvert.converter.api.config

/**
 * Strategy used when `konvert.enforce-not-null = true` and Konvert has to map
 * from a nullable source type to a non-nullable target type.
 *
 * - [ASSERTION_OPERATOR] uses the Kotlin `!!` operator and throws a raw [NullPointerException].
 * - [REQUIRE_NOT_NULL] wraps the access in [requireNotNull] and throws an [IllegalArgumentException]
 *   with a descriptive message generated by the processor.
 */
enum class EnforceNotNullStrategy {

    /**
     * Use the Kotlin not-null assertion operator (`!!`).
     *
     * This strategy is kept for backwards compatibility and may no longer be the default
     * in a future Konvert version. Prefer [REQUIRE_NOT_NULL] for clearer error messages.
     */
    @Deprecated(
        message = "ASSERTION_OPERATOR is kept for backwards compatibility and may no longer be the default in a future Konvert version. Prefer REQUIRE_NOT_NULL.",
        replaceWith = ReplaceWith("EnforceNotNullStrategy.REQUIRE_NOT_NULL")
    )
    ASSERTION_OPERATOR,

    /**
     * Use [requireNotNull] with a generated error message.
     */
    REQUIRE_NOT_NULL
}
