source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`

gem "just-the-docs", "0.12.0"

group :jekyll_plugins do
    gem 'jekyll-asciidoc'
    gem 'jekyll-target-blank', '~> 2.0' # plugin to always open external links in new tabs
end
