package io.mcarle.lib.kmapper.converter.api

typealias Priority = Int

const val LOWEST_PRIORITY = Int.MAX_VALUE
const val HIGHEST_PRIORITY = Int.MIN_VALUE
const val SAME_TYPE_PRIORITY = 1000
const val DEFAULT_KMAPPER_NO_ANNOTATION_PRIORITY = 2000
const val DEFAULT_KMAPTO_PRIORITY = 3000
const val DEFAULT_KMAPFROM_PRIORITY = 4000
const val DEFAULT_KMAPPER_PRIORITY = 5000
const val DEFAULT_CONVERTER_PRIORITY = 10000
